#!/usr/bin/env bash

# Certificate Authority
openssl genrsa -des3 -out rootCA.key -passout pass:secret 2048
openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 1024 -out rootCA.pem -config rootCA.csr.cnf -passin pass:secret

# # Server
openssl req -new -sha256 -nodes -out server.csr -newkey rsa:2048 -keyout server.key -config server.csr.cnf
openssl x509 -req -in server.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out server.crt -days 500 -sha256 -extfile v3.ext -passin pass:secret
